export const PHASES = [
    {
        id: 1,
        name: "The Oblivious Commuter",
        choice: "Not Possible",
        intention: "Without Intention",
        summary: "Forced path, no desire for the scent.",
        description: "There is only one road home, and it passes right by the bakery. You walk this road because you have to, but you just ate and have a cold—you have no desire to smell the fresh bread. The pleasure is forced upon you by your route, but your heart is completely indifferent.",
        gradientVertical: "linear-gradient(to bottom, #d97706, #b45309)",
        gradientHorizontal: "linear-gradient(to right, #d97706, #b45309)",
        glowColor: "rgba(180, 83, 9, 0.2)",
        hasDetour: false,
        hasDesire: false,
    },
    {
        id: 2,
        name: "The Indifferent Wanderer",
        choice: "Possible",
        intention: "Without Intention",
        summary: "Has a detour, but walks the bakery path without caring.",
        description: "There is an alternate route home that completely avoids the bakery. However, you happen to take the bakery route anyway. Even so, you still have no intention or desire to enjoy the smell. You could have easily avoided it, but the scent means nothing to you.",
        gradientVertical: "linear-gradient(to bottom, #3b82f6, #1d4ed8)",
        gradientHorizontal: "linear-gradient(to right, #3b82f6, #1d4ed8)",
        glowColor: "rgba(29, 78, 216, 0.2)",
        hasDetour: true,
        hasDesire: false,
    },
    {
        id: 3,
        name: "The Captive Craver",
        choice: "Not Possible",
        intention: "With Intention",
        summary: "Forced path, but actively enjoys the scent.",
        description: "There is only one road home, passing the bakery. This time, however, you are starving. You must walk this way to get home, but as you pass the bakery, you actively breathe in and deeply enjoy the scent. The route is forced upon you, but your desire is fully engaged.",
        gradientVertical: "linear-gradient(to bottom, #e11d48, #9f1239)",
        gradientHorizontal: "linear-gradient(to right, #e11d48, #9f1239)",
        glowColor: "rgba(159, 18, 57, 0.2)",
        hasDetour: false,
        hasDesire: true,
    },
    {
        id: 4,
        name: "The Deliberate Seeker",
        choice: "Possible",
        intention: "With Intention",
        summary: "Has a detour, but deliberately chooses the scent.",
        description: "You have two completely different routes home. Because you are hungry, you deliberately choose the route that passes the bakery specifically to enjoy the wonderful smell. You could have avoided it, but you actively sought out the pleasure. This is the ultimate, complete form of desire.",
        gradientVertical: "linear-gradient(to bottom, #059669, #065f46)",
        gradientHorizontal: "linear-gradient(to right, #059669, #065f46)",
        glowColor: "rgba(6, 95, 70, 0.2)",
        hasDetour: true,
        hasDesire: true,
    }
];
